# Generated by Django 4.2.16 on 2024-10-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_candidate_user_alter_comment_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='태그명')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='삭제여부'),
        ),
        migrations.AlterField(
            model_name='post',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='삭제여부'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='posts.hashtag', verbose_name='해시태그 목록'),
        ),
    ]
